export const publicRoutes = [
  '/login',
  '/signup',
  '/complete-signup',
  '/sso-signup',
  '/sent-email',
  '/activate',
  '/resetpassword',
  '/success',
  '/activate-failed',
  '/forgot-password',
  '/verify-mfa',
  '/sso-activation',
  '/oidc',
];
